### ISSUE TITLE
Add wineasio

### ISSUE THREAD

**Issue by simonvanderveldt** [gentoo-audio/audio-overlay#130]
Seems the current/new repo is located at https://github.com/jhernberg/wineasio

**Comment by simonvanderveldt** [comment]
I'm working on a wineasio ebuild but there are some things on the (new) wine packages side that need to be fixed first. Mainly `eselect wine` doesn't create the relevant symlinks to the wine libs in `/usr/lib`. I'm in touch with the wine maintainers on IRC to see how we can get this fixed

**Comment by simonvanderveldt** [comment]
Created a gentoo bug to track the necessary changes needed for eselect wine https://bugs.gentoo.org/638414

**Comment by Lucretia** [comment]
Wineasio needs to be rebuilt on every wine update.

**Comment by simonvanderveldt** [comment]
Yeah, I'm going to close this one, it's too much of a hassle, in general and specifically given the lack of infrastructure for build wine libs in gentoo. Also personally I don't use it and don't see any reason to use it, using wine for pro audio is a bad idea imho.

**Comment by Lucretia** [comment]
The wine ebuilds would need an asio use flag, this would then enable the wineasio/asio-sdk dependencies. There is an existing wineasio ebuild from a long time ago on zugaina.
