### ISSUE TITLE
add giada

### ISSUE THREAD

**Issue by mrVanDalo** [gentoo-audio/audio-overlay#15]
https://www.giadamusic.com/

**Comment by simonvanderveldt** [comment]
Do you actively use it?
I made an ebuild an tried it recently, but didn't really get along with it. Don't remember if it had technical issues or if I didn't like the workflow though :x

**Comment by mrVanDalo** [comment]
Yeah I played around with it as well a while ago, but this thing changes it's version very quickly. so I wanted to give it another try.

**Comment by simonvanderveldt** [comment]
K. Unfortunately I've already deleted the ebuild for it, it wasn't that hard though.

**Comment by mrVanDalo** [comment]
No I can remember it as well just simple cmake i think

**Comment by simonvanderveldt** [comment]
@mrVanDalo Have you tried Luppp? https://github.com/openAVproductions/openAV-Luppp
It only does samples though, whereas giada also does MIDI.

**Comment by mrVanDalo** [comment]
I tried it a long time ago, but couldn't get use to it. Dont know it was unstable or I did not get the workflow.

**Comment by mrVanDalo** [comment]
To long open and done nothing, will close it, if somebody wants to create this package, just make a new ticket or open this one.
