### ISSUE TITLE
add helm

### ISSUE THREAD

**Issue by mrVanDalo** [gentoo-audio/audio-overlay#16]
http://tytel.org/helm/

**Comment by simonvanderveldt** [comment]
I'll create an ebuild for this. Will not include VST support for now, for that we first need to address #18

**Comment by simonvanderveldt** [comment]
I just noticed this already exists in the gentoo tree, it's just very out of date.
I'll keep this issue open as an reminder that we should create a PR to update Helm upstream

**Comment by mrVanDalo** [comment]
It would be better to push an up to date package in here, and create an issue to push it to the upstream

**Comment by simonvanderveldt** [comment]
Closing this, I'm working on getting helm bumped upstream, see https://bugs.gentoo.org/638150
