### ISSUE TITLE
Add Steinberg's VST3 SDK

### ISSUE THREAD

**Issue by simonvanderveldt** [gentoo-audio/audio-overlay#18]
Some plugins (like helm, see #16) need it for VST support, will need to check the license situation. AFAIK it's now dual licensed.
See https://github.com/steinbergmedia/vst3sdk
Also read up on it here https://linuxmusicians.com/viewtopic.php?f=24&t=16854&sid=0aec9e3d500a48a2a9be83e6ac491171

**Comment by mrVanDalo** [comment]
Sweet I would take a look at it in some weeks.
When I'm starting with it, I would assign it to me. But if somebody else likes to do it, feel free to assign it to you.

**Comment by simonvanderveldt** [comment]
@mrVanDalo Sounds good to me.
I did notice that for example Helm now includes the VST3 SDK sources inside it's own repo. Not sure if other projects do the same, but this might make the need for a VST3 SDK a bit less of an immediate issue.

**Comment by mrVanDalo** [comment]
Nice, but I think it's a good idea to provide an ebuild vor vst3. But I agree we should plan this ticket after the helm package is done (if helm does not need vst3 from outside)

**Comment by simonvanderveldt** [comment]
So far we don't seem to have any other projects apart from Helm that need the VST3 SDK and since Helm already includes it I'm going to close this issue. If a new package pops up that needs it we can add it then.
