### ISSUE TITLE
media-sound/cadence has missing dependency on dev-python/PyQt5

### ISSUE THREAD

**Issue by jason-oliveira** [gentoo-audio/audio-overlay#184]
Application will not build without dev-python/PyQt5. Please add to dependencies in ebuild.

**Comment by simonvanderveldt** [comment]
Thanks for letting us know. I already have an open PR to fix this (#177) but it's taking too long on CI and times out, so so far it hasn't been merged. I'll do a final check locally and force-merge it so it at least works for everyone and will then take some time to try to figure out what to do with our CI, don't really want a failing master :(
