### ISSUE TITLE
media-sound/cadence needs two dependencies added to ebuild

### ISSUE THREAD

**Issue by jason-oliveira** [gentoo-audio/audio-overlay#195]
These may seem trivial to most, but for those of us using CloverOS (or other minimal gentoo distributions), dbus is not built-in by default to most packages. Therefore, the bare minimum cadence requires is media-sound/jack2 built with dbus, and dev-python/PyQt5 built with dbus, in order to operate with more than greyed-out buttons. Accordingly, these need to be added as dependencies in the ebuild.

**Comment by simonvanderveldt** [comment]
Thanks for the report!
Does this mean Cadence doesn't work with JACK1? I believe that doesn't support dbus. Or is that not the case?

Thanks for the pointer about PyQt5, looking at the code both PyQt5's DBus support as well as dbus-python are used, I'll make sure that gets updated.

**Comment by jason-oliveira** [comment]
according to [this conversation](https://linuxmusicians.com/viewtopic.php?t=17176), there is a jackdbus for jack1, but I'm not sure if it's been merged upstream, and can't really be arsed to check if the jack1 package builds it. 

However, I do know that cadence is explictly looking for jackdbus, which would likely narrow it down to the jack2 version, as they apparently work differently. Is anyone using jack1 with this overlay?

**Comment by simonvanderveldt** [comment]
In general we assume JACK1 and JACK2 to behave the same and allow everyone to use whichever version they prefer.
But if there are hard dependencies then that's obviously not going to work :)
I'll check with falk

**Comment by simonvanderveldt** [comment]
Checked with falk, Cadence does indeed rely on jackdbus and since that's not in JACK1 (and the patch/commits for adding it currently doen't apply) that means Cadence is currently only compatible with JACK2.
I'll update the ebuild accordingly.
