### ISSUE TITLE
add patchage package

### ISSUE THREAD

**Issue by mrVanDalo** [gentoo-audio/audio-overlay#2]

**Comment by mrVanDalo** [comment]
alternative use patchmatrix

**Comment by simonvanderveldt** [comment]
@mrVanDalo Have you ever tried [Catia](http://kxstudio.linuxaudio.org/Applications:Catia?)?

**Comment by mrVanDalo** [comment]
@simonvanderveldt also a valid alternative for the beginning

**Comment by simonvanderveldt** [comment]
Patchage is already in the main gentoo repo https://github.com/gentoo/gentoo/tree/master/media-sound/patchage
