### ISSUE TITLE
Important ebuilds from proaudio

### ISSUE THREAD

**Issue by anemal** [gentoo-audio/audio-overlay#22]
Hi all,

thanks for your efforts to keep audio production on gentoo alive. 

I wanted to send a small list of packages from the old proaudio overlay, which I think of are important for serious audio production on gentoo:

media-libs/zita-resampler
media-sound/zita-at1
     Autotuner

media-sound/guitarix2
media-sound/jack_capture
    Guitaramplifier

app-emulation/wineasio
media-libs/asio-sdk
     For realtime usage of windows software over wine (like EZDrummer).

media-sound/jsampler
     Frontend for linuxsampler

media-sound/mididings
     To setup midi routes

**Comment by marcan** [comment]
wineasio, asio-sdk, and mididings are on my list, so those should be going in as soon as I get a chance :)

**Comment by mrVanDalo** [comment]
This is duplicated of #9

**Comment by simonvanderveldt** [comment]
@anemal Can you add these as a comment to #9? Thanks!

**Comment by anemal** [comment]
Sure. I'll copy the list to [#9](https://github.com/gentoo-audio/audio-overlay/issues/9).
