### ISSUE TITLE
Add ADLMIDI and OPNMIDI plugins?

### ISSUE THREAD

**Issue by simonvanderveldt** [gentoo-audio/audio-overlay#229]
See https://github.com/jpcima/ADLplug

**Comment by jpcima** [comment]
Of course you should. :wink: 
I've just tagged the beta.3 and will put the released files out as soon as time permits. Let me know if I can help in any way.

Just a thing: please do not name the package "ADLMIDI". That name designated is the original MIDI file player software. ADLplug is in fact software based on a fork "libADLMIDI", which rewraps that library as instrument plugin, pretty much.
At the core is still the ADLMIDI code of Joel Yliluoma, with a pile of enhancements made on our side.

**Comment by simonvanderveldt** [comment]
@jpcima Wow, props for noticing this issue so quickly! :D

Thanks for the pointer on the name, we'll make sure to name it correctly.
I'll make sure to create an issue if we run into problems. Thanks for being proactive about this! :)

**Comment by spinnylights** [comment]
@simonvanderveldt Hihi, how far along did this get? I recently switched to Gentoo and need ADLplug+OPNplug for an in-progress music project. I'm happy to write an ebuild + submit a pull request if you don't already have this going.

**Comment by simonvanderveldt** [comment]
@spinnylights didn't really get far with it, so if you'd want to create a PR that would be great! :)
It's using CMake so should be relatively easy to create an ebuild for.

**Comment by spinnylights** [comment]
@simonvanderveldt Okay, sure thing! Yeah, I built it from source a while ago and remember it not being too bad. I suppose I'm off to it then ^_^

**Comment by spinnylights** [comment]
All right, here we are: https://github.com/gentoo-audio/audio-overlay/pull/290
