### ISSUE TITLE
Add proaudio specific profile?

### ISSUE THREAD

**Issue by simonvanderveldt** [gentoo-audio/audio-overlay#24]
Follow up from #9. Shall we add a pro audio specific profile? And if so, what should it do?

**Comment by mrVanDalo** [comment]
> Honestly I don't see why proaudio profiles should have anything to do with init system or desktop environment choice. Just enable audio-related flags and that's it. Going into init systems and desktops is making a lot of unnecessary assumptions. Desktop-specific variants should just inherit from the standard desktop profiles.

I'm on the side of @marcan.

**Comment by domichel** [comment]
> IMHO if we want an audio-specific profile, we need to start from scratch and consider what should be in there, starting with the basics like jack and lv2.
You are right, that's fine for me.

> Desktop-specific variants should just inherit from the standard desktop profiles
We must keep in mind than in portage, we have
`/usr/portage/profiles/targets/desktop/gnome/` and `/usr/portage/profiles/targets/desktop/plasma/`, both with parent pointing to `/usr/portage/profiles/targets/desktop/`.

That imply we must have 3 profiles: `profiles/targets/desktop/gnome/`, `/usr/portage/profiles/targets/desktop/plasma/` and `profiles/targets/desktop/`, each of them with the audio flags and pointing to the related portage profile. If symlinks do works here, we can even maintain the USE flags only into the desktop profile, and use a symlink or 2 into the plasma and gnome profiles,,

**Comment by domichel** [comment]
I just made a pull request, so you can review it.

**Comment by simonvanderveldt** [comment]
I did some thinking on this and I think the initial question "Shall we add a pro audio specific profile?" is something we jumped over too fast.

We should determine what the benefits to the users would be and what would need to be done to make it possible and guarantee to the users that it keeps working.

From the discussion in #28 I think we can conclude the only thing it would bring would be some predefined USE flags.
Looking at #28 a serious amount of files is needed to make it work. Which also means we'd need to somehow guarantee that all of them would work.

My suggestion would be to not add profiles to the overlay. I don't think it's worth the time/effort just to add a couple of USE flags. The USE flags should be a user's own choice anyway.

What we can (and probably should anyway) do is document properly, ideally on the gentoo wiki, what a pro audio/audio production setup should consist of and have a suggestion for useful USE flags there.

**Comment by mrVanDalo** [comment]
I use Funtoo, so it will not affect me.

**Comment by marcan** [comment]
I have to concur with @simonvanderveldt. While I appreciate the convenience of having profiles, we're talking about two USE flags right now (more would follow, but still just USE flags). As long as we're talking about just global USE flags an not just more complicated settings (such as a several package-specific flags, etc.), I think we're better off just documenting the recommendation and letting people enable them the normal way.

**Comment by domichel** [comment]
For me, an audio overlay must not only provide packages which are not in portage, but also offer a convenient way to install them. It is where a profile can be useful.

About the amount of files in the profile. A big part are symlinks and for the other files, it will be no more maintenance than to maintain a documentation up-to-date.

Anyway, if the majority doesn't want a profile, I will just ask those with commit right into the old pro-audio overlay to not remove the profile of that overlay.

**Comment by marcan** [comment]
I think the point is that `eselect profile set <whatever>` isn't really any less convenient than `euse -E <whatever>`, and the latter works for all profiles, not just those we decide to provide audio versions for.

**Comment by simonvanderveldt** [comment]
> I think the point is that eselect profile set <whatever> isn't really any less convenient than euse -E <whatever>, and the latter works for all profiles, not just those we decide to provide audio versions for.

:+1: 

I've added #31 to not forget to document how to setup gentoo for proaudio. This should include an overview of relevant USE flags. And could include a copy-pastable snippet of `euse -E <use flags>` to address this.
