### ISSUE TITLE
Merge new/changed ebuilds from a PR during tests

### ISSUE THREAD

**Issue by simonvanderveldt** [gentoo-audio/audio-overlay#27]
I'd very much like to merge new or changed ebuilds from a PR as a minimal validation that the ebuild is actually working.

This needs the following things:
- Determine which ebuilds are new/changed vs the base/target branch
- Set necessary USE flags
- emerge the ebuilds

The main issue here is setting the necessary USE flags. To do this automatically we'd need to figure out a way to parse `IUSE` combined with `REQUIRED_USE`, which will be quiet a bit of work I imagine.
Alternatively we can add an matching `tests/<category>/<package>.env` file that we use to define the basic USE flags in and source the before the emerge.

Any feedback or other suggestions to make this work?

**Comment by simonvanderveldt** [comment]
Eventually I'd like to test all possible USE flag combinations. I just got pointed to tatt, that among other things can generate a shell script to emerge a package with all USE flag combinations. Might be possible to leverage that to make it work.
Relevant code here https://github.com/kensington/tatt/blob/master/tatt/usecombis.py#L11

**Comment by simonvanderveldt** [comment]
> The main issue here is setting the necessary USE flags. To do this automatically we'd need to figure out a way to parse IUSE combined with REQUIRED_USE, which will be quiet a bit of work I imagine.
> Alternatively we can add an matching tests/<category>/<package>.env file that we use to define the basic USE flags in and source the before the emerge.

I think I'm going to go with the USE flag file per package in `tests/<category>/<package>`. This way we can define relevant/required USE flags easily and enable these tests right now instead of waiting till there's an automated way to determine the required USE flags.
It means we manually need to add a file, but it also means we have full control over the "default" USE flags we test.

**Comment by mrVanDalo** [comment]
I like automation, if it very smart and can pick up the context without any problems.
But I don't like stupid smartness which does not pick up the context, in this situation I like to have it explicit. 

Because we are in the process of creating these acceptance tests, I would like to have them explicit as well. 

@simonvanderveldt We should think about documenting the whole thing, with a small step by step guide.

**Comment by simonvanderveldt** [comment]
👍 
I'll make sure I update the docs within the same PR

**Comment by simonvanderveldt** [comment]
Fixed in #26
