### ISSUE TITLE
media-plugins/sorcer

### ISSUE THREAD

**Issue by mazes-80** [gentoo-audio/audio-overlay#291]
Migrate ebuild to EAPI 7

Add src_prepare
src_prepare() {
        sed -i -e "s:lib/lv2:$(get_libdir)/lv2:" -e '/RELEASE_BUILD/s/ON/OFF/' CMakeLists.txt || die
        cmake-utils_src_prepare
}
 "s:lib/lv2:$(get_libdir)/lv2:" : allow plugin to be installed under /usr/lib64/lv2 (and recognized as system lv2 plugin)
'/RELEASE_BUILD/s/ON/OFF/' : allows to uses CFLAGS defined under make.conf

For now I applied this only to live ebuild, but it should also work for the other one.

**Comment by mazes-80** [comment]
media-plugins/fabla: also needs it:

src_prepare() {
        cmake-utils_src_prepare
        sed -i "s:lib/lv2:$(get_libdir)/lv2:" CMakeLists.txt
}

**Comment by simonvanderveldt** [comment]
@mazes-80 Are there issues with the current ebuild?

P.S. you can use triple backticks for code blocks

**Comment by mazes-80** [comment]
The ebuild still compiles fine, and install fine. 
But it isn't listed by lv2ls when using 17.1 profile on amd64
Libraries  are now installed /usr/lib64, so lv2 directory is /usr/lib64/lv2
Most lv2 plugins hardcode path lib/lv2, and do not take care of LIBDIR, $(get_libdir) softens it.
The latest snippet of code allows most of plugins using cmake build system to be fixed.

Second fix for sorcer, allows user defined "system C/CXX flags" to be used instead of those hardcoded in the build system.
