### ISSUE TITLE
media-sound/helm does not compile

### ISSUE THREAD

**Issue by Zeroneca** [gentoo-audio/audio-overlay#293]
helm doesn't compile with GCC 9 because of JUCE.

Works with the following commit: https://github.com/WeAreROLI/JUCE/commit/4e0adb2af8b424c43d22bd431011c9a6c57d36b6

Working with user patch (copy to /etc/portage/patches/media-sound/helm/gcc9.patch):
[compile.txt](https://github.com/gentoo-audio/audio-overlay/files/3908103/compile.txt)

**Comment by simonvanderveldt** [comment]
Upstream PR to fix this https://github.com/mtytel/helm/pull/233

@Zeroneca I'd like to try to ping upstream once more. If there's no response with a week we can include the patch. Does that sound OK to you?

**Comment by simonvanderveldt** [comment]
FYI This has been fixed by gentoo upstream :)
https://bugs.gentoo.org/686108
