### ISSUE TITLE
Failure when building carla

### ISSUE THREAD

**Issue by dr-diem** [gentoo-audio/audio-overlay#294]
Hi, I'm still new to ebuilds so not clear why this is failing (might it be that v2.0.0 is released now?). Anyway, when building against Gentoo profile 17.1 amd64, the emerge fails with:
```
fatal: unable to access 'https://github.com/falkTX/Carla.git/': Operation timed out after 300000 milliseconds with 0 out of 0 bytes received
 * ERROR: media-sound/carla-9999::audio-overlay failed (unpack phase):
 *   Unable to fetch from any of EGIT_REPO_URI
```
The URL works as-is in a browser, so I cannot see why it is failing. Here are my build and debug logs:

[build.log](https://github.com/gentoo-audio/audio-overlay/files/3935751/build.log)
[eclass-debug.log](https://github.com/gentoo-audio/audio-overlay/files/3935752/eclass-debug.log)

Thanks,

Ian

**Comment by dr-diem** [comment]
Gah, my bad entirely, I had misconfigured my HTTPS_PROXY env var so git fetch was failing. Sorry for the noise.

**Comment by simonvanderveldt** [comment]
No problem at all :)
