### ISSUE TITLE
Document proaudio setup

### ISSUE THREAD

**Issue by simonvanderveldt** [gentoo-audio/audio-overlay#31]
It might be useful to document what a proper proaudio setup entails and how to get a gentoo install setup in such a way.

To have as much exposure as possible we should do so on the gentoo wiki.

**Comment by simonvanderveldt** [comment]
There are already some items related to proaudio/audio production on the gentoo wiki, I'll post them here for reference
- https://wiki.gentoo.org/wiki/Music_Production
- https://wiki.gentoo.org/wiki/Project:Sound/How_to_Enable_Realtime_for_Multimedia_Applications
- https://wiki.gentoo.org/wiki/ALSA#JACK_audio_connection_kit

**Comment by mrVanDalo** [comment]
lets use github pages for that.

**Comment by domichel** [comment]
As audiodef pointed out on IRC, there is definitely a broad set of use flags that help make a Gentoo box better suited for pro audio application. See [Manual install: installing the gentoo installation files](http://gentoostudio.org/?s=manualinstall&p=files)
`USE="a52 aac aacplus alsa audacious bindist cdda cddb cdio consolekit corefonts dbus dirac dssi dts dv dvd encode equalizer faac ffmpeg fftw flac fluidsynth freesound g3dvl gif gtk gudev hwdb icu id3 id3tag ieee1394 jack jackmidi jpeg ladspa lame libsamplerate lv2 mad matroska midi minizip mp3 mp4 mpeg mpg123 musepack musicbrainz netjack ogg opengl pcre16 png policykit python qt3support qt4 qt5 quicktime realtime rubberband schroedinger shine shout skins sndfile soundtouch svg taglib theora tiff timidity truetype twolame udev usb vamp vcd vorbis wav wavpack X x264 xine xkb xml xvfb xvid xvmc -introspection -pulseaudio -xscreensaver"`

**Comment by mrVanDalo** [comment]
https://gentoo-audio.github.io/ < just created a repository to document topics.

**Comment by simonvanderveldt** [comment]
Going to close this, docs can be added to the gentoo wiki by whoever wants to pick up this task (not limited to contributors to this repo/organisation)
