### ISSUE TITLE
media-sound/mididings-99999999: cannot find -lboost_python

### ISSUE THREAD

**Issue by nick87720z** [gentoo-audio/audio-overlay#312]
Issue is that there is no exactly -lboost_python.
If it were -lboost_python27, -lboost_python36 etc, it would probably work.

**Comment by simonvanderveldt** [comment]
Thanks for the report.
Noticed this on CI as well (https://circleci.com/gh/gentoo-audio/audio-overlay/1241), will have a look at possible fixes.
