### ISSUE TITLE
broken packages in proaudio due to libclthreads movement

### ISSUE THREAD

**Issue by nick87720z** [gentoo-audio/audio-overlay#318]
Portage tree has dev-libs/libclthreads, but list of packages in proaudio still depends on media-libs/libclthreads:
aliki, ambdec, jconvolver, tetraproc, zita-rev1
ebumeter, jace, japa, jkmeter, jmeters, jnoisemeter, yass, zita-at1

**Comment by simonvanderveldt** [comment]
Hi @nick87720z. Thanks for the report, but there are no ebuilds in this overlay that use libclthreads.
If you have issues with ebuilds from the proaudio overlay you should file a bug there, see http://proaudio.tuxfamily.org/wiki/index.php?title=Main_Page

**Comment by nick87720z** [comment]
I remember, proaudio mailing list was told to be barely watched. But when I try to visit bugtracker, I get database access problem:
http://proaudio.tuxfamily.org/bugs

Yet mailing list is described as good to report bugs, propose patches, etc - like here for audio-overlay. Is it ok, to report via mail?

**Comment by simonvanderveldt** [comment]
@nick87720z I'm sorry but I don't know. @domichel might know more he's the maintainer of the proaudio overlay and the accompanying infrastructure
