### ISSUE TITLE
Check compatibility with 17.1 profiles

### ISSUE THREAD

**Issue by simonvanderveldt** [gentoo-audio/audio-overlay#323]
Seems like they should be installed in `/usr/lib64`/`/usr/lib32` (or `/usr/lib` for 32bit? :confused: )
See https://www.gentoo.org/support/news-items/2019-06-05-amd64-17-1-profiles-are-now-stable.html and https://wiki.gentoo.org/wiki/Project:AMD64/Multilib_layout

**Comment by mazes-80** [comment]
I think 17.1 is stable since monthes now, hopefully nothing forces the switch.
Fixing packages will not break 17.0 as the get_libdir helper will work on both profiles.

Another plugin I needed to fix: media-plugins/artyfx
src_prepare() {
        sed -i -e "s:lib/lv2:$(get_libdir)/lv2:" CMakeLists.txt || die
        cmake-utils_src_prepare
}

**Comment by simonvanderveldt** [comment]
media-plugins/fable is the only package left that needs fixing for this :)
