### ISSUE TITLE
ntk-9999 to python 3

### ISSUE THREAD

**Issue by Lucretia** [gentoo-audio/audio-overlay#442]
In the above ebuild, changing:

```
PYTHON_COMPAT=( python2_7 python3_4 )
```
to

```
PYTHON_COMPAT=( python3_{4,5,6,7,8,9} )
```

Works fine, but in the 1.3.1000 does not.

**Comment by simonvanderveldt** [comment]
FYI The whole ntk ebuild broke because @original-male removed the repo :(

**Comment by original-male** [comment]
@simonvanderveldt Please do not @ mention me. Read the post on LAD if you're curious about what was done to my project. But good luck getting a post of your own through to that list if you have anything to say about it... Linux Audio is dead.

**Comment by simonvanderveldt** [comment]
@original-male Did you remove the repository at https://git.tuxfamily.org/non as well?

**Comment by Lucretia** [comment]
@simonvanderveldt https://github.com/falkTX/ntk

**Comment by original-male** [comment]
@simonvanderveldt Please do not @ mention me. If you'd like to discuss this, I'd be happy to answer your questions at length. But I think the appropriate venue for that discussion would be the Linux Audio Developers mailing list. Why don't you post your question to me there (be sure to mention me by name), and I'll see if I can see your question. You may be interested to know that David Runge, one of the group of three (including Filipe Coelho [their leader] and Nils Hilbrect) who hijacked my projects and slandered me in the name of the Linux Audio Consortium, moderates this list. I really believe you'll learn everything you need to know about the nature of this situation just by posting your question to LAD (and failing to see it appear, or getting a taunting rejection message).
