### ISSUE TITLE
ladish-9999 fails to build here...

### ISSUE THREAD

**Issue by CaptainBloodz** [gentoo-audio/audio-overlay#454]
Build log:

Emerging (1 of 1) media-sound/ladish-9999::audio-overlay
 * Using python3.7 to build
>>> Unpacking source...
 * Repository id: lad_ladish.git
 * To override fetched repository properties, use:
 *   EGIT_OVERRIDE_REPO_LAD_LADISH
 *   EGIT_OVERRIDE_BRANCH_LAD_LADISH
 *   EGIT_OVERRIDE_COMMIT_LAD_LADISH
 *   EGIT_OVERRIDE_COMMIT_DATE_LAD_LADISH
 * 
 * Fetching https://git.nedk.org/lad/ladish.git ...
git fetch https://git.nedk.org/lad/ladish.git +HEAD:refs/git-r3/HEAD
From https://git.nedk.org/lad/ladish
 * [new tag]           0.1                   -> 0.1
 * [new tag]           0.2                   -> 0.2
 * [new tag]           before_command_queue_integration -> before_command_queue_integration
 * [new tag]           dbus_helpers_gpl_afl  -> dbus_helpers_gpl_afl
 * [new tag]           ladish-0.3            -> ladish-0.3
 * [new tag]           ladish-0.3-rc20100906 -> ladish-0.3-rc20100906
 * [new tag]           ladish-0.3-rc20101030 -> ladish-0.3-rc20101030
 * [new tag]           ladish-0.3-rc20101203 -> ladish-0.3-rc20101203
 * [new tag]           ladish-0.3-rc20101231 -> ladish-0.3-rc20101231
 * [new tag]           ladish-0.3-rc20110102 -> ladish-0.3-rc20110102
 * [new tag]           ladish-1              -> ladish-1
git symbolic-ref refs/git-r3/media-sound/ladish/0/__main__ refs/git-r3/HEAD
 * Checking out https://git.nedk.org/lad/ladish.git to /var/tmp/portage/media-sound/ladish-9999/work/ladish-9999 ...
git checkout --quiet refs/git-r3/HEAD
GIT update -->
   repository:               https://git.nedk.org/lad/ladish.git
   at the commit:            4be0b87b4cb353002ff96cbc3cef67245a9b7a1a
>>> Source unpacked in /var/tmp/portage/media-sound/ladish-9999/work
>>> Preparing source in /var/tmp/portage/media-sound/ladish-9999/work/ladish-9999 ...
 * Applying ladish-9999-disable-gladish.patch ...                      [ ok ]
 * Applying 001-ladish-9999-readlink-aliasing.patch ...
patching file daemon/procfs.c
Hunk #1 FAILED at 39.
Hunk #2 FAILED at 152.
2 out of 2 hunks FAILED -- saving rejects to file daemon/procfs.c.rej  [ !! ]
 * ERROR: media-sound/ladish-9999::audio-overlay failed (prepare phase):
 *   patch -p1  failed with /etc/portage/patches/media-sound/ladish-9999/001-ladish-9999-readlink-aliasing.patch
 * 
 * Call stack:
 *               ebuild.sh, line  125:  Called src_prepare
 *             environment, line 3283:  Called default
 *      phase-functions.sh, line  855:  Called default_src_prepare
 *      phase-functions.sh, line  920:  Called __eapi6_src_prepare
 *             environment, line  321:  Called eapply_user
 *             environment, line 1362:  Called eapply '/etc/portage/patches/media-sound/ladish-9999/001-ladish-9999-readlink-aliasing.patch'
 *             environment, line 1332:  Called _eapply_patch '/etc/portage/patches/media-sound/ladish-9999/001-ladish-9999-readlink-aliasing.patch'
 *             environment, line 1270:  Called __helpers_die 'patch -p1  failed with /etc/portage/patches/media-sound/ladish-9999/001-ladish-9999-readlink-aliasing.patch'
 *   isolated-functions.sh, line  112:  Called die
 * The specific snippet of code:
 *   		die "$@"
 * 
 * If you need support, post the output of `emerge --info '=media-sound/ladish-9999::audio-overlay'`,
 * the complete build log and the output of `emerge -pqv '=media-sound/ladish-9999::audio-overlay'`.
 * The complete build log is located at '/var/log/portage/media-sound:ladish-9999:20210302-061931.log.gz'.
 * For convenience, a symlink to the build log is located at '/var/tmp/portage/media-sound/ladish-9999/temp/build.log.gz'.
 * The ebuild environment file is located at '/var/tmp/portage/media-sound/ladish-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/media-sound/ladish-9999/work/ladish-9999'
 * S: '/var/tmp/portage/media-sound/ladish-9999/work/ladish-9999'

>>> Failed to emerge media-sound/ladish-9999, Log file:

>>>  '/var/log/portage/media-sound:ladish-9999:20210302-061931.log.gz'

**Comment by CaptainBloodz** [comment]
amd64 /var/db/repos/audio-overlay/media-sound/ladish/files # ll
total 24
-rw-r--r-- 1 root root  612 août  15  2018 ladish-1-add-includes-for-getrlimit.patch
-rw-r--r-- 1 root root 1114 août  15  2018 ladish-1-configure-libdir.patch
-rw-r--r-- 1 root root 1579 févr. 28 21:32 ladish-1-disable-gladish.patch
-rw-r--r-- 1 root root 5860 févr. 28 21:32 ladish-1-python3.patch
-rw-r--r-- 1 root root 1577 févr. 28 21:32 ladish-9999-disable-gladish.patch

So 001-ladish-9999-readlink-aliasing patch files currently missing in files/

**Comment by CaptainBloodz** [comment]
Silly me:
issue due to uncompatible local /etc/portage/patch file.
Building fine once removed.

Sorry for the noise.

**Comment by simonvanderveldt** [comment]
Np :)
