### ISSUE TITLE
Missing PYTHON_COMPAT=( python3_9 ) support

### ISSUE THREAD

**Issue by NexAdn** [gentoo-audio/audio-overlay#460]
Some packages from the overlay are still missing support for python3.9 while it has become the default python version in the Gentoo main tree yesterday. Furthermore, some of those packages still have support for very old python versions, some of which aren't available in the Gentoo tree anymore.

`grep -R PYTHON_COMPAT * | grep -v "python3_9"` says:

```
grep -R PYTHON_COMPAT * | grep -v "python3_9" 
media-libs/pyliblo/pyliblo-0.10.0-r2.ebuild:PYTHON_COMPAT=( python3_{6,7,8} )
media-libs/libmonome/libmonome-9999.ebuild:PYTHON_COMPAT=( python2_7 python3_4 python3_5 python3_6 python3_7 )
media-libs/libmonome/libmonome-1.4.3.ebuild:PYTHON_COMPAT=( python2_7 python3_4 python3_5 python3_6 python3_7 )
media-plugins/bitrot/bitrot-9999.ebuild:PYTHON_COMPAT=( python3_6 python3_7 python3_8 )
media-plugins/deteriorate-lv2/deteriorate-lv2-1.0.7.ebuild:PYTHON_COMPAT=( python3_4 python3_5 python3_6 python3_7 )
media-plugins/deteriorate-lv2/deteriorate-lv2-1.0.6.ebuild:PYTHON_COMPAT=( python2_7 python3_4 python3_5 python3_6 )
media-plugins/deteriorate-lv2/deteriorate-lv2-9999.ebuild:PYTHON_COMPAT=( python3_4 python3_5 python3_6 python3_7 )
media-sound/serialosc/serialosc-1.4.1.ebuild:PYTHON_COMPAT=( python2_7 python3_4 python3_5 python3_6 )
media-sound/serialosc/serialosc-9999.ebuild:PYTHON_COMPAT=( python2_7 python3_4 python3_5 python3_6 )
media-sound/carla/carla-9999-r1.ebuild:PYTHON_COMPAT=( python3_{6,7,8} )
media-sound/carla/carla-2.2.0.ebuild:PYTHON_COMPAT=( python3_{6,7,8} )
media-sound/carla/carla-2.1.1.ebuild:PYTHON_COMPAT=( python3_{6,7,8} )
media-sound/cadence/cadence-9999-r7.ebuild:PYTHON_COMPAT=( python3_{6,7,8} )
media-sound/ladish/ladish-1-r2.ebuild:PYTHON_COMPAT=( python3_6 python3_7 python3_8 )
media-sound/ladish/ladish-9999.ebuild:PYTHON_COMPAT=( python3_6 python3_7 python3_8 )
x11-libs/ntk/ntk-1.3.1000.ebuild:PYTHON_COMPAT=( python2_7 python3_4 )
```

so the following packages are affected and should probably be updated:

* [ ] media-libs/pyliblo
* [ ] media-libs/libmonome
* [ ] media-plugins/bitrot
* [ ] media-plugins/deteriorate-lv2
* [ ] media-sound/serialosc
* [ ] media-sound/carla
* [ ] media-sound/cadence
* [ ] media-sound/ladish
* [ ] x11-libs/ntk

For most of these packages, I'd suggest removing python3_{4,5} from PYTHON_COMPAT completely (after all, they're not even available in the Gentoo tree anymore) and add python3_9 to PYTHON_COMPAT whereever it's possible (which is probably all of those packages).

**Comment by dr-diem** [comment]
+1 for this - I am dependent upon Carla to support the EQ10Q parametric equalizer to correct my studio room audio signature.
