### ISSUE TITLE
Add Cadence/Catia/Claudia

### ISSUE THREAD

**Issue by simonvanderveldt** [gentoo-audio/audio-overlay#47]
http://kxstudio.linuxaudio.org/Applications:Cadence

The Cadence project/repo also contains these applications
- http://kxstudio.linuxaudio.org/Applications:Claudia
- http://kxstudio.linuxaudio.org/Applications:Catia
- http://kxstudio.linuxaudio.org/Applications:Catarina

Since these currently can't be installed separately, they'll be part of the ebuild as well.
I'll see if I can convince falk to split them up.

**Comment by simonvanderveldt** [comment]
I alread have a working ebuild for this, need to bump it to EAPI 6 and create a PR to add it

**Comment by audiodef** [comment]
I have working Cadence and Carla ebuilds.

**Comment by simonvanderveldt** [comment]
I have the ebuild ready, but this is blocked by #45. Will create a PR once that one is merged.
