### ISSUE TITLE
media-sound/carla doesn't include carla-host-plugin.pc

### ISSUE THREAD

**Issue by jason-oliveira** [gentoo-audio/audio-overlay#478]
in order for many packages to take advantage of carla, they need the carla-host-plugin.pc (among others) installed to their /usr/lib(64)/pkgconfig/ directory.

Unfortunately, this ebuild does not handle these files, which should be installed, [and *are* installed in distros like Arch Linux](https://archlinux.org/packages/community/x86_64/carla/files/). 

This is currently breaking zrythm, which I am attempting to create an ebuild for (to submit here), but requires carla-host-plugin.pc for much of its functionality.

**Comment by jason-oliveira** [comment]
[According to Arch's PKGBUILD](https://archlinux.org/packages/community/x86_64/carla/files/), src_install() needs to take the following parameters from their make install:

`make DEFAULT_QT=5  DESTDIR="${pkgdir}/" PREFIX=/usr install`

When I manually build/install the app from source, all files are installed correctly.

**Comment by NexAdn** [comment]
Is this still up to date? On my machine, the .pc file gets installed correctly. Apart from that, the command line in our `src_install()` is almost the same as the one you've mentioned and none of the options in Arch's PKGBUILD should have an influence on the installation of this .pc file anyways (and neither should the options we use).

**Comment by NexAdn** [comment]
Closing as stale. The issue seems resolved from my point of view and there was no response in several months. If this issue still persists, please reopen this issue.
