### ISSUE TITLE
Cannot install bitwig-studio

### ISSUE THREAD

**Issue by SameExpert** [gentoo-audio/audio-overlay#480]
While installing `bitwig-studio`, the following error occurs:
~~~
chmod: cannot access '/var/tmp/portage/media-sound/bitwig-studio-4.0.4/image/opt/bitwig-studio/lib/jre/lib/*': No such file or directory
~~~

The `*` wildcard is not being expanded.

**Comment by SameExpert** [comment]
After reading through Gentoo forums threads and issues of other ebuilds, I came to know that `fperms` does not expand the `*` wildcard.

**Comment by BakedSnake** [comment]
Same for me, I'm sticking with 3.3.10 for now.

**Comment by simonvanderveldt** [comment]
Thanks for the report, PR with fix is up :)

**Comment by simonvanderveldt** [comment]
@KevinThomas0 Any idea how this is possible? Did you not emerge/test/use the ebuild yourself?

**Comment by KevinThomas0** [comment]
@simonvanderveldt that is very strange, I did install and have been using Bitwig from that ebuild for months with no problems.

**Comment by KevinThomas0** [comment]
Yeah so it looks like wildcards aren't supported but they work for some people I guess, and I was one of those people? Very weird.

**Comment by simonvanderveldt** [comment]
Very strange. Anyway, it's fixed now :)
