### ISSUE TITLE
Document tests

### ISSUE THREAD

**Issue by simonvanderveldt** [gentoo-audio/audio-overlay#57]
We should properly document which tests we have and how to run them. Including what every script does.
Should probably include a "Don't run scripts other than these locally" warning!

**Comment by mrVanDalo** [comment]
A : "Don't run scripts other than these locally" would be greate ! :D 

What can I do? Should I bring the presentation page in a state to add this stuff easier ?

**Comment by simonvanderveldt** [comment]
I guess I'll move the script one shouldn't run locally to a subdir, that way the separation is a bit more explicit.
And I'll add a readme to the test directory a well so we have clear docs on what does what and how to use/run it. Don't think we need to publish this to the org website.
