### ISSUE TITLE
New version v3.2.0 of praxis-live available

### ISSUE THREAD

**Issue by simonvanderveldt** [gentoo-audio/audio-overlay#77]
A new version v3.2.0 of praxis-live is available since 2017-08-18 17:22:57+00:00. For more details see https://github.com/praxis-live/praxis-live/releases

**Comment by mrVanDalo** [comment]
I know, but I don't have time right now to do this. It's already on my todo list :D

**Comment by simonvanderveldt** [comment]
(FYI these bump messages are created by Travis, they just have my name on it ;))
