### ISSUE TITLE
bump bitwig studio to version 2

### ISSUE THREAD

**Issue by mrVanDalo** [gentoo-audio/audio-overlay#8]

**Comment by mrVanDalo** [comment]
pull-request by : #14

**Comment by simonvanderveldt** [comment]
@mrVanDalo FYI if you create a PR and mention something like `fixes #8` in the relevant commit message GitHub will do all of this for you, no need to manage closing issues yourself.
See https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by mrVanDalo** [comment]
Yeah but than I have to remember this ticket. I close it because the Pull-request is open.

**Comment by simonvanderveldt** [comment]
> I close it because the Pull-request is open

yeah, you don't have to. Once the PR gets merged github will close it for you if you reference it in a commit.
That way you also have a guaranteed reference on both sides (the issue and the PR)

**Comment by mrVanDalo** [comment]
Ok I'll try not to forget it.
