### ISSUE TITLE
media-sound/ladish break portage and the old overlay

### ISSUE THREAD

**Issue by domichel** [gentoo-audio/audio-overlay#82]
The current ladish ebuild break both portage and the old overlay. ladish and lash provides both lash and liblash.

In the old overlay, a virtual/liblash ebuild was used. New ebuilds can depend on it. It depend on one of lash-original or ladish. The overlay's lash ebuild is a fake with the same depend than the virtual. This was done to satisfy portage and the overlay.

In portage, it is only media-sound/lash, and all portage ebuilds with a lash depend are depending on media-sound/lash. The overlay must not break portage, which imply we must use a virtual like in the old overlay, or like in https://bugs.gentoo.org/show_bug.cgi?id=442916

At that time, I think we must also satisfy the overlay, because most audio pro user will use both overlays, and if the new one break the old one and portage, they will stop to use the new one.

I can make a push request later, maybe that week, or next week. But if someone can fix it before, he is welcome.

**Comment by mrVanDalo** [comment]
I personally don't care about the `proaudio` overlay.
I don't get what you mean by break portage?

I agree that if ladish is the successor of lash there should be a `virtual` package and the `ladish` package should block the `lash` package.

**Comment by simonvanderveldt** [comment]
@domichel What do you mean with break portage? I have `media-sound/ladish` installed from this overlay and that works fine. `media-sound/ladish` already blocks `media-sound/lash` if the `lash` USE flag is enabled.

Also, I discussed this on IRC on `#gentoo-dev-help` and the consensus was to not use a virtual unless there are 5+ packages that depend on it. Instead simply define both dependencies in the packages that need it `|| ( media-sound/lash media-sound/ladish )` and that's it. Since we only have two packages in the overlay that support lash/ladish we don't use a virtual.

**Comment by domichel** [comment]
The issue is the overlay break existing stuff. And users are using existing
stuff.

Also, this is just a matter of time before we get more than 5 packages with
a lash depend, which imply a virtual is justified.

That break portage because portage's ebuild have a hard depend on lash, and
if you install ladish from the overlay at the same time, both lash and
ladish will install liblash. I have not tried that, but it look obvious
that only one liblash implementation can be installed, and portage want
lash, so we must provide a way to trick it.

Le mercredi 30 août 2017, Simon van der Veldt <notifications@github.com> a
écrit :

**Comment by mrVanDalo** [comment]
I can only see on package that depends on lash. I can't even see one that depends on ladish.

```
$ equery depends media-sound/ladish media-sound/lash
 * These packages depend on media-sound/ladish:

 * These packages depend on media-sound/lash:
media-sound/fluidsynth-1.1.6-r1 (lash ? >=media-sound/lash-0.5.4-r2[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?])
```

**Comment by mrVanDalo** [comment]
`equery d <pgk> -a` shows these infos on my machine:

I don't have the `old-proaudio-overlay` on board.

```
* These packages depend on media-sound/ladish:
media-sound/sequencer64-0.93.0 (lash ? media-sound/ladish[lash])
media-sound/sequencer64-9999 (lash ? media-sound/ladish[lash])
```

``` 
* These packages depend on media-sound/lash:
media-plugins/calf-0.0.60 (lash ? media-sound/lash)
media-plugins/calf-9999 (lash ? media-sound/lash)
media-sound/amsynth-1.3.2 (lash ? media-sound/lash)
media-sound/amsynth-1.5.1 (lash ? media-sound/lash)
media-sound/amsynth-1.6.4 (lash ? media-sound/lash)
media-sound/amsynth-1.7.0 (lash ? media-sound/lash)
media-sound/fluidsynth-1.1.6-r1 (lash ? >=media-sound/lash-0.5.4-r2[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?])
media-sound/hydrogen-0.9.5 (lash ? media-sound/lash)
media-sound/jack-keyboard-2.5 (lash ? media-sound/lash)
media-sound/jack-rack-1.4.7-r1 (lash ? >=media-sound/lash-0.5)
media-sound/jack-rack-1.4.8_rc1 (lash ? >=media-sound/lash-0.5)
media-sound/jack-smf-utils-1.0 (lash ? media-sound/lash)
media-sound/seq24-0.9.2-r1 (lash ? >=media-sound/lash-0.5)
media-sound/seq24-0.9.3 (lash ? >=media-sound/lash-0.5)
media-sound/sequencer64-0.93.0 (lash ? media-sound/lash)
media-sound/sequencer64-9999 (lash ? media-sound/lash)
media-sound/specimen-0.5.2_rc3-r1 (lash ? media-sound/lash)
media-sound/specimen-0.5.2_rc3-r2 (lash ? media-sound/lash)
media-sound/timemachine-0.3.1 (lash ? >=media-sound/lash-0.5)
media-sound/timemachine-0.3.3 (lash ? >=media-sound/lash-0.5)
media-sound/timemachine-0.3.3-r1 (lash ? >=media-sound/lash-0.5)
media-sound/vkeybd-0.1.18d (lash ? media-sound/lash)
media-sound/zynaddsubfx-3.0.1 (lash ? media-sound/lash)
```

**Comment by simonvanderveldt** [comment]
> That break portage because portage's ebuild have a hard depend on lash, and
> if you install ladish from the overlay at the same time, both lash and
> ladish will install liblash. I have not tried that, but it look obvious
> that only one liblash implementation can be installed, and portage want
> lash, so we must provide a way to trick it.

This is already fixed, because `media-sound/ladish[lash]` blocks `media-sound/lash`.

Also, there's nothing we can do about this except to either add ladish to the gentoo tree or fork the ebuilds from the gentoo tree that currently depend on `media-sound/lash` and update them so they depend on both (or a virtual).
Obviously I prefer the first option. And I would only consider the second option for individual packages if 1. users actually start asking about this and 2. it's clear that ladish won't be added to the gentoo tree

**Comment by domichel** [comment]
Le jeudi 31 août 2017, Simon van der Veldt <notifications@github.com> a
écrit :

> That break portage because portage's ebuild have a hard depend on lash, and
> if you install ladish from the overlay at the same time, both lash and
> ladish will install liblash. I have not tried that, but it look obvious
> that only one liblash implementation can be installed, and portage want
> lash, so we must provide a way to trick it.
>
> This is already fixed, because media-sound/ladish[lash] blocks
> media-sound/lash.
>
> Also, there's nothing we can do about this except to either add ladish to
> the gentoo tree or fork the ebuilds from the gentoo tree that currently
> depend on media-sound/lash and update them so they depend on both (or a
> virtual).
>
>
> Obviously I prefer the first option. And I would only consider the second
> option for individual packages if 1. users actually start asking about this
> and 2. it's clear that ladish won't be added to the gentoo tree
>

The only needed forked portage package is lash, which must be renamed as
lash-original. In addition we must provide a fake lash ebuild in order to
satisfy portage. That lash ebuild will only depend on lash||ladish. This is
the way we choose in the old overlay, and it was done that way in order to
not break portage.

For me, to break or not break portage is a design choice, and i will not
support an overlay that break portage.

**Comment by domichel** [comment]
Le jeudi 31 août 2017, Dominique Michel <dominique.c.michel@gmail.com> a
écrit :

>
>
> Le jeudi 31 août 2017, Simon van der Veldt <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> a écrit :
>
>> That break portage because portage's ebuild have a hard depend on lash,
>> and
>> if you install ladish from the overlay at the same time, both lash and
>> ladish will install liblash. I have not tried that, but it look obvious
>> that only one liblash implementation can be installed, and portage want
>> lash, so we must provide a way to trick it.
>>
>> This is already fixed, because media-sound/ladish[lash] blocks
>> media-sound/lash.
>>
>> Also, there's nothing we can do about this except to either add ladish to
>> the gentoo tree or fork the ebuilds from the gentoo tree that currently
>> depend on media-sound/lash and update them so they depend on both (or a
>> virtual).
>>
>>
>> Obviously I prefer the first option. And I would only consider the second
>> option for individual packages if 1. users actually start asking about this
>> and 2. it's clear that ladish won't be added to the gentoo tree
>>
>
> The only needed forked portage package is lash, which must be renamed as
> lash-original. In addition we must provide a fake lash ebuild in order to
> satisfy portage. That lash ebuild will only depend on lash||ladish
>
> Sorry on lash-original||ladish

>
>
. This is the way we choose in the old overlay, and it was done that way in

**Comment by simonvanderveldt** [comment]
> For me, to break or not break portage is a design choice, and i will not
> support an overlay that break portage.

Maybe we have different definitions of the work "break" but nothing in this (or hopefully any) overlay can and will break portage.
Also, no user install can or will be broken when they use this overlay, they will just get a blocker when trying to install `media-sound/ladish`, nothing major.
If that's the case and ladish hasn't landed in the gentoo tree at that point that user can file an issue here and we can determine what to do at that point in time.

**Comment by nick87720z** [comment]
Just noticed this issue. Up to now i have older proaudio overlay, from tuxfamily, and there is media-sound/lash-9998 ebuild, which has USE=ladish. When this use flag is enabled, media-sound/lash-9998 acts as virtual, pulling in ladish with USE=lash.

Of course, there is no convenient way for user to figure out, e.g., via gpo.zugaina.org (they need to check proaudio git dir in separate step). Imho, that ebuild doesn't look broken - enough to include to this overlay too.

**Comment by simonvanderveldt** [comment]
This is the same things as answered in #191 

Quoting here for peopling finding this issue through the search:
> If you want to use packages that have LASH support and you have LADISH installed the easiest way to achieve that is to add `media-sound/lash` to `/etc/portage/package.provided`
