### ISSUE TITLE
New version v3.3.0 of praxis-live available

### ISSUE THREAD

**Issue by simonvanderveldt** [gentoo-audio/audio-overlay#99]
A new version v3.3.0 of praxis-live is available since 2017-10-13 18:50:10+00:00. For more details see https://github.com/praxis-live/praxis-live/releases

**Comment by mrVanDalo** [comment]
as described in IRC, I don't have a gentoo anymore where I can test the bumped version. So somebody else should bump version.

**Comment by simonvanderveldt** [comment]
Since our maintainer left and no one else within the team uses praxis-live I think we'll have to mark praxis-live as an abandoned package. Going to close this issue for now. Will probably remove praxis-live from the overlay soon.
